name: Qwiet AI Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  # This is necessary to access your code
        uses: actions/checkout@v3
        
      - name: Run Qwiet AI Scan
        uses: sandy-qwietai/qwietai-actions@main
        with:
          app_name: "url-shortener"
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}